#!/usr/bin/env bash
# Bash script that will display information about subdomains.

infodisplay () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    infodisplay "$2.$1" "$2"
else
    infodisplay "www.$1" "www"
    infodisplay "lb-01.$1" "lb-01"
    infodisplay "web-01.$1" "web-01"
    infodisplay "web-02.$1" "web-02"
fi