#!/usr/bin/env bash
# Script that Install nginx web server 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo /etc/init.d/nginx restart
