#!/usr/bin/env bash
#Script that pings an IP address passed as an argument:
#_Accepts a string as an argument.
#_Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS},
#_if no argument passed.
#_Ping the IP 5 times.

if [ "$1" == "" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
