#!/usr/bin/env bash
#Script that displays the content of the file /etc/passwd:
#_username
#_user id
#_Home directory path for the user
while read pass; 
do
      echo "$pass" | cut -d':' -f1,3,6
done < /etc/passwd
