#!/usr/bin/env bash
#Script that displays the content of the file /etc/passwd
while NJC=: read -r user pw uid gid info home cmd
do
	echo "The user $user is part of the $gid gang, lives in $home and rides $cmd. $uid's place is protected by the passcode $pw, more info about the user here: $info"
done < /etc/passwd
