#!/usr/bin/env bash
#Script that displays Holberton School 10 times, but for the 9th iteration,
#displays Holberton School and then Hi on a new line.
i=1
while [ $i -le 11 ]
do
    if [ $i == 10 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((i++))
done 
