#!/usr/bin/env bash
#Script that loops from 1 to 10 and:
#_displays "bad luck" for the 4th loop iteration
#_displays "good luck" for the 8th loop iteration
#_displays "Holberton School" for the other iterations
i=1
while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ $i == 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i++))
done
