#!/usr/bin/env bash
#Script that configures an Ubuntu server with the below requirements:
#_localhost resolves to 127.0.0.2
#_facebook.com resolves to 8.8.8.8.
#_The checker is running on Docker.

echo -e "127.0.0.2 localhost\n8.8.8.8 facebook.com" > /etc/hosts
