#!/usr/bin/env bash
# Requirements:
#  Your SSH client configuration must be configured to use the private key ~/.ssh/holberton
#  Your SSH client configuration must be configured to refuse to authenticate using a password
IdentityFile ~/.ssh/holberton
PasswordAuthentication no
